# Generated by Django 5.2.1 on 2025-05-21 12:14

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano', models.CharField(max_length=20, verbose_name='Ano')),
                ('sistema', models.CharField(blank=True, max_length=100, verbose_name='Sistema')),
                ('tipo_chave', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Chave')),
                ('transponder', models.CharField(blank=True, max_length=100, verbose_name='Transponder')),
                ('immo_part_replacement', models.CharField(blank=True, max_length=100, verbose_name='Substituição da Peça IMMO')),
                ('frequencia', models.CharField(blank=True, choices=[('', '---------'), ('315', '315 MHz'), ('433', '433 MHz')], max_length=3, verbose_name='Frequência')),
                ('add_key', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=45, verbose_name='Add Key')),
                ('read_password', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=45, verbose_name='Read Password')),
                ('remote_learning', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=45, verbose_name='Remote Learning')),
                ('key_lost', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allOBD', 'All support OBD method'), ('partOBD', 'Part of the models support OBD method'), ('allBENCH', 'All support on-bench/boot method'), ('partBENCH', 'Part of the models support on-bench/boot method'), ('notreq', 'Not required'), ('none', 'Not supported')], max_length=45, verbose_name='Key Lost')),
            ],
        ),
    ]
