# Generated by Django 5.2.1 on 2025-05-22 15:14

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_veiculo_add_key_alter_veiculo_key_lost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='add_key',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allOBD', 'allOBD'), ('partOBD', 'partOBD'), ('allBENCH', 'allBENCH'), ('partBENCH', 'partBENCH')], max_length=33, verbose_name='Add Key'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='key_lost',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allOBD', 'allOBD'), ('partOBD', 'partOBD'), ('allBENCH', 'allBENCH'), ('partBENCH', 'partBENCH')], max_length=33, verbose_name='Key Lost'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='read_password',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allOBD', 'allOBD'), ('partOBD', 'partOBD'), ('allBENCH', 'allBENCH'), ('partBENCH', 'partBENCH')], max_length=33, verbose_name='Read Password'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='remote_learning',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('allOBD', 'allOBD'), ('partOBD', 'partOBD'), ('allBENCH', 'allBENCH'), ('partBENCH', 'partBENCH')], max_length=33, verbose_name='Remote Learning'),
        ),
    ]
