# Generated by Django 5.2.3 on 2025-06-26 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencia_erro.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, help_text='Data em que o problema foi reportado', verbose_name='Data de reporte')),
                ('deadline', models.DateField(blank=True, help_text='Prazo para resolução do problema', null=True, verbose_name='Prazo')),
                ('finished', models.DateField(blank=True, help_text='Data em que o problema foi resolvido', null=True, verbose_name='Concluído em')),
                ('technical', models.CharField(default='Não identificado', max_length=100, verbose_name='Técnico')),
                ('responsible', models.CharField(default='Não identificado', max_length=100, verbose_name='Responsável')),
                ('device', models.CharField(default='N/A', max_length=100, verbose_name='Equipamento')),
                ('area', models.CharField(default='N/A', max_length=20, verbose_name='Área')),
                ('serial', models.CharField(blank=True, default='N/A', max_length=20, null=True, verbose_name='Serial')),
                ('brand', models.CharField(blank=True, default='N/A', max_length=100, null=True, verbose_name='Marca')),
                ('model', models.CharField(blank=True, default='N/A', max_length=100, null=True, verbose_name='Modelo')),
                ('year', models.CharField(blank=True, default='N/A', max_length=100, null=True, verbose_name='Ano')),
                ('version', models.CharField(blank=True, default='N/A', max_length=100, null=True, verbose_name='Versão')),
                ('problem_detected', models.TextField(default='Não identificado', verbose_name='Problema detectado')),
                ('status', models.CharField(choices=[('DONE', 'Concluído'), ('LATE', 'Atrasado'), ('PROGRESS', 'Em progresso'), ('REQUESTED', 'Requisitado')], default='REQUESTED', max_length=20)),
                ('feedback_technical', models.TextField(blank=True, default='Não identificado', null=True, verbose_name='Feedback Técnico')),
                ('feedback_manager', models.TextField(blank=True, default='Não identificado', null=True, verbose_name='Feedback Manager')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencia_erro.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['status'], name='ocorrencia__status_c96f89_idx'), models.Index(fields=['device'], name='ocorrencia__device_19753e_idx'), models.Index(fields=['data'], name='ocorrencia__data_c4c464_idx')],
            },
        ),
    ]
