# Generated by Django 5.2.1 on 2025-06-04 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia_erro', '0003_alter_record_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-data'], 'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data de reporte', verbose_name='Data de reporte'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('DONE', 'Concluído'), ('LATE', 'Atrasado'), ('PROGRESS', 'Em progresso'), ('REQUESTED', 'Requisitado')], default='REQUESTED', max_length=20),
        ),
    ]
