# Generated by Django 5.2.1 on 2025-06-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia_erro', '0004_alter_record_options_alter_record_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='year',
            field=models.CharField(blank=True, default='N/A', help_text='Ano', max_length=100, null=True, verbose_name='Ano'),
        ),
    ]
