# Generated by Django 5.2.1 on 2025-06-09 14:25

import ocorrencia_erro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia_erro', '0005_alter_record_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='deadline',
            field=models.DateField(blank=True, default=ocorrencia_erro.models.default_deadline, help_text='Data de previsão para término', null=True, verbose_name='Prazo'),
        ),
    ]
