# Generated by Django 5.2.3 on 2025-06-17 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, default='SEM DADO', max_length=30, verbose_name='CPF/CNPJ')),
                ('tel', models.CharField(blank=True, default='SEM DADO', max_length=30, verbose_name='Telefone')),
                ('equipamento', models.CharField(blank=True, default='', max_length=100, verbose_name='Equipamento')),
            ],
        ),
    ]
