# Generated by Django 5.2.1 on 2025-05-27 13:26

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('tel', models.IntegerField(max_length=20, verbose_name='Telefone')),
                ('equipamento', models.CharField(verbose_name='Equipamento')),
                ('status', multiselectfield.db.fields.MultiSelectField(choices=[('vencendo', 'A vencer'), ('vencido', 'Vencido'), ('direito', 'Tem direito')], max_length=24, verbose_name='Status')),
            ],
        ),
    ]
