# Generated by Django 5.2.1 on 2025-05-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacao_veiculo', '0002_alter_cliente_cnpj_alter_cliente_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('vencendo', 'A vencer'), ('vencido', 'Vencido'), ('direito', 'Tem direito')], verbose_name='Status'),
        ),
    ]
