# Generated by Django 5.2.1 on 2025-05-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacao_veiculo', '0003_alter_cliente_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='feedback',
            field=models.CharField(blank=True, max_length=255, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='equipamento',
            field=models.CharField(max_length=100, verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('vencendo', 'A vencer'), ('vencido', 'Vencido'), ('direito', 'Tem direito')], max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
    ]
