# Generated by Django 5.2.1 on 2025-05-27 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacao_veiculo', '0004_cliente_data_cliente_email_cliente_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
