# Generated by Django 5.2.1 on 2025-05-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacao_veiculo', '0005_alter_cliente_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('vencendo', 'A vencer'), ('vencido', 'Vencido'), ('direito', 'Tem direito')], default='direito', max_length=10, verbose_name='Status'),
        ),
    ]
