# Generated by Django 5.2.1 on 2025-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacao_veiculo', '0006_alter_cliente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, default='SEM DADO', max_length=30, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default='SEM DADO', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='feedback',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('vencendo', 'SUPORTE A VENCER'), ('vencido', 'SUPORTE VENCIDO'), ('direito', 'SUPORTE LIBERADO')], default='direito', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tel',
            field=models.CharField(blank=True, default='SEM DADO', max_length=30, verbose_name='Telefone'),
        ),
    ]
