# Generated by Django 5.2.1 on 2025-05-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('situacao_veiculo', '0010_alter_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='status',
        ),
    ]
