# Generated by Django 5.2.1 on 2025-05-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situacao_veiculo', '0011_remove_cliente_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='equipamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Equipamento'),
        ),
    ]
