name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
              cd /home/ubuntu/Sistema_Suporte
              
              echo "=== DEBUG DO AMBIENTE ==="
              whoami
              pwd
              env | grep -i db
              env | grep -i django
              
              echo "=== VERIFICANDO .env ==="
              ls -la .env
              cat .env
              
              echo "=== VERIFICANDO CONEXÃO MYSQL ==="
              mysql --version
              mysql -u root -p -e "SHOW DATABASES;" || echo "Erro MySQL"